### ISSUE TITLE
Audio lights flares up when scene transitions to darkness/daylight 

### ISSUE THREAD

**Issue by Nordiii** [BlitzKraig/fvtt-CommunityLighting#13]
Audio lights flare up when the scene gets transitioned into darkness / daylight. 
The light source goes out as soon as the transition is completed.

**How to reproduce:**

1. Open any scene and place an audio light which should only show when music is playing.
2. Use the default scene transition buttons on the left hot bar.

**Comment by Nordiii** [comment]
This also happens when creating a new light source/dragging existing once.

**Comment by BlitzKraig** [comment]
This should be fixed as a result of some other fixes.
Thanks!
