### ISSUE TITLE
On starting the world

### ISSUE THREAD

**Issue by jacobjorvang** [BlitzKraig/fvtt-CommunityLighting#17]
DevTools failed to load SourceMap: Could not load content for http://x.x.x.x:xxxxx/modules/CommunityLighting/dependencies/pixi-filters.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by BlitzKraig** [comment]
Hi jacobjorvang,

This is just a warning that no sourcemap has been provided for the minified JS file. Your browser only checks for this file when you open DevTools, and it can be safely ignored.

Thanks for the report!
