### ISSUE TITLE
Scene stops rendering on updating token lighting

### ISSUE THREAD

**Issue by Lazytron** [BlitzKraig/fvtt-CommunityLighting#2]
Still testing, but scene stops rendering (freezes, does not load on activation) on token lighting udate in some cases. Finding the token through console and deleting fixes it, but ive been able to repro a couple of times with this particular set of values.  ![image](https://user-images.githubusercontent.com/32400728/97064992-e1df6800-156f-11eb-8790-04ce3f9ff665.png)

**Comment by BlitzKraig** [comment]
Thanks for the details, I'll take a look at that animation and see what I've missed

**Comment by BlitzKraig** [comment]
This should be fixed in 0.1.1, thanks for the report!
