### ISSUE TITLE
Audio trigger light does not work with 'Large File Streaming' setting enabled

### ISSUE THREAD

**Issue by MarlQ** [BlitzKraig/fvtt-CommunityLighting#23]
As in the title, audio lights do not trigger on any track which has the 'Large File Streaming' setting enabled.

**Comment by BlitzKraig** [comment]
Hi,

This is a known limitation, LFS audio is routed through the HTML5 API, meaning it's not possible to connect an analyser node to it.

Thanks for the feedback!

**Comment by MarlQ** [comment]
Ahh shame. I'd have lots more use for it if it would work. But when I tried without LFS not only the application froze, but my whole PC...

**Comment by BlitzKraig** [comment]
Unfortunately it's simply not possible to make it work due to the inability to connect an analyser. This may change with the audio improvements coming in core 0.8

Thanks for the feedback
