### ISSUE TITLE
Game Freezes with some of the lights when placed on Actors

### ISSUE THREAD

**Issue by GambetTV** [BlitzKraig/fvtt-CommunityLighting#3]
All the lights seem to work fine when using the Draw Light Source tool, but when adding light sources to tokens/actors, most break the game in some way.

Blurred Torch and Alternate Torch work fine. Police Flash doesn't use blue/white light, and only kind of blinks. RGB works OK, except when the token moves, then it just turns pure white. The rest cause the game to completely freeze, though you're still able to double click tokens to open up their character sheet or Token Configuration, although undoing the light does nothing. Using the Mouse Wheel to scroll in and out of the map only causes the token HUD to increase/decrease in size, and leave the token which is weird.

**Comment by BlitzKraig** [comment]
Thanks for the report, I'll look into that and get back to you

**Comment by zLaddeus** [comment]
I have a similar issue.

When I added an Emit value to an actor, even without using some of the new animations.

![image](https://user-images.githubusercontent.com/71599968/97082067-2c5ff380-1607-11eb-927d-85dcdfbb09a2.png)

The scene froze, and can't be opened again just becomes a grey screen. 
Disabling the module fixes this.

**Comment by BlitzKraig** [comment]
Thanks for giving some more detail, that will be helpful. I'll be on my pc this evening, so I'll take a look and hopefully update

**Comment by BlitzKraig** [comment]
This should be fixed in 0.1.1, thanks for the report!
