### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by tjlanza** [BlitzKraig/fvtt-CommunityLighting#30]
While it doesn't seem to adversely affect anything, version 0.3.1 of this module throws a warning in FVTT0.7.9 on every load:

`DevTools failed to load SourceMap: Could not load content for https://[my.domain.here]/modules/CommunityLighting/dependencies/pixi-filters.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

It's always the very first thing in the console, even before the "Foundry VTT" ASCII art. I've uninstalled and reinstalled the module to confirm it wasn't a bad download. System does not appear to be a factor; I've tried it with three different ones.

**Comment by BlitzKraig** [comment]
Hi tjlanza, I've just not provided the mapping file for pixi-filters, this error only fires when the devtools are open because it attemps to find it for debugging purposes.

In normal operation, this check won't be done. Thanks for the feedback!
