### ISSUE TITLE
Soundboard integration doesn't work on audio pulse in 0.8.x

### ISSUE THREAD

**Issue by Keodant** [BlitzKraig/fvtt-CommunityLighting#35]
Band and source sections don´t appear in the audio pulse light animation type. Here is console and demostration,
![2](https://user-images.githubusercontent.com/57667078/120708496-04d0e380-c492-11eb-8fb7-4af6ae8b2925.png)

![Untitled](https://user-images.githubusercontent.com/57667078/120708358-d81ccc00-c491-11eb-8fe0-ce5f42704c94.png)

Also audio pulse doesn't work at all

**Comment by BlitzKraig** [comment]
Hi,
Are you running CommunityLighting 0.3.5?

**Comment by Keodant** [comment]
> Hi,
> Are you running CommunityLighting 0.3.5?

Werid, i was using 0.3.3, i thougt all my modules where up to date. Well, sorry for not checking that blitz
