### ISSUE TITLE
BUG: Changing Light Types requires an F5 refresh to see it

### ISSUE THREAD

**Issue by GambetTV** [BlitzKraig/fvtt-CommunityLighting#36]
Changing light types in Tokens or Light Sources directly will glitch out and either not change the light, freeze the light, or do some kind of weird halvies between the two light types. Fixing it requires you to refresh the page. I'm using the latest version of this module and Foundry, using the Foundry App to run it on Windows 10.

**Comment by BlitzKraig** [comment]
Hi,
Can you elaborate further on "changing light type directly?"
Do you mean changing via the light config, or via code/macro?

**Comment by BlitzKraig** [comment]
Hi Gambet,
Thanks for the feedback, jumped in and ran a quick test, I missed something silly with the monkeypatch changes...

Should work in 0.3.6, just released
