### ISSUE TITLE
K is not defined when trying to update module

### ISSUE THREAD

**Issue by roi007leaf** [BlitzKraig/fvtt-CommunityLighting#40]
![image](https://user-images.githubusercontent.com/17231451/122329865-cda30d80-cf3a-11eb-8086-f5819b16685e.png)

**Comment by BlitzKraig** [comment]
Urgh, trying to be too clever with my release workflow.
Will fix today, thanks for the feedback

**Comment by BlitzKraig** [comment]
This should be fixed in 0.4.4, thanks
